### ISSUE TITLE
Issues with `prlimit` on number of open files and `LD_PRELOAD`

### ISSUE THREAD

**Issue by drinkcat** [termux/termux-exec#34]
For uutils/coreutils, tests are run with somewhat aggressive prlimit on the number of open files (`NOFILE`).

For some reason, these tests started failing after a termux update (at least at the same time as #33). Setting `LD_PRELOAD=` fixes the issue.

Some sample test cases on Linux follow.

Running cat on many input files, we should only really need 1 extra fd on top of stdin/out/err, so 4 should be enough. And of course, the linker will need 1 fd to load libraries (but only temporarily).
```
$ touch x
$ prlimit -n3:3 cat x x x x x
cat: error while loading shared libraries: libc.so.6: cannot open shared object file: Error 24
$ prlimit -n4:4 cat x x x x x
```

But paste needs 5 (with 2 parameters) for example:
```
$ prlimit -n4:4 paste x x
paste: x: Too many open files
$ prlimit -n5:5 paste x x
```

I tried to increase the number of fd by 2 (we already bake in _some_ margin, I added more...), but that was still not enough to make the tests pass, so I'm not sure what's going on, but it seems like there are quite a few fds that end up getting open?

We've disabled these tests for now, but it'd be nice if you had time to investigate ,-)

I saw at least 2 fd leaks, but it's possible there is more (and that those don't actually matter?!):
 - https://github.com/termux/termux-core-package/blob/2261b3dc5c1d7c5d597abf2b474ebb7fe8ccaa1f/lib/termux-core_nos_c_tre/src/unix/os/selinux/UnixSeLinuxUtils.c#L56
 - https://github.com/termux/termux-exec-package/commit/3300bfba6445e61bb647bd911467ba40c9e851d9#r154213188

**Comment by agnostic-apollo** [comment]
Thanks for the report. The fd leaks should be fixed with https://github.com/termux/termux-exec-package/commit/3f3a69fc3960842c89f7c90114dcb290e4e1afc9 and https://github.com/termux/termux-core-package/commit/9431e452. However, these won't trigger in any normal circumstances, and possibly only in some rare case. What's more likely is the `open()`/`fopen()` call failing before that, in which case there would be no leak. The `/proc/self/attr/current` file is accessible on all Android versions till now and file header is not opened for system binaries anymore since 3300bfba for which the `open()` call may fail on certain devices. `termux-exec` only opens an fd for these two situations and fds are closed immediately, any leaks should likely show with `ls /proc/self/fd`, but only the standard fds are listed with it.

Issue is all the libraries being loaded by the linker. The number of libraries opended will depend on whether `/system/bin/cat` or `$TERMUX__PREFIX/bin/cat` is run, and will also vary on different android versions and vendors. Check the logs below to see if you raise the **soft limit** (not hard) to the number of libraries the linker will open, the `cat` command works. You would likely need root access to modify the hard limits. Note that linker may close some libraries after opening them, so total number of libraries open at any given time would be lower the the total `open` calls. Additionally, some libraries may not exist as well. You can also check return value of `openat()` call.

The issue is also reproducible on `termux-exec` `v1.0` and so `v2.0.0` did not break anything AFAIS,

```shell
~ $ strace -f prlimit --verbose -n30 /system/bin/cat x x x x x 2>&1 | grep open | grep -E '/lib(64
)/' | sort | uniq | wc  -l
22
~ $ strace -f prlimit --verbose -n21 /system/bin/cat x x x x x 2>&1 | grep open | grep -E '/lib(64
)/'
openat(AT_FDCWD, "/odm/lib64/vndk-sp", O_RDONLY|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or dir
ectory)
openat(AT_FDCWD, "/vendor/lib64/vndk-sp", O_RDONLY|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or 
directory)
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/odm/lib64/vndk-sp", O_RDONLY|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or dir
ectory)
openat(AT_FDCWD, "/vendor/lib64/vndk-sp", O_RDONLY|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or 
directory)
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libcrypto.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libz.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/liblog.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libprocessgroup.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libselinux.so", O_RDONLY|O_CLOEXEC) = 7
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 8
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 9
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 10
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 11
openat(AT_FDCWD, "/system/lib64/libbase.so", O_RDONLY|O_CLOEXEC) = 12
openat(AT_FDCWD, "/system/lib64/libcgrouprc.so", O_RDONLY|O_CLOEXEC) = 13
openat(AT_FDCWD, "/system/lib64/libpcre2.so", O_RDONLY|O_CLOEXEC) = 14
openat(AT_FDCWD, "/system/lib64/libpackagelistparser.so", O_RDONLY|O_CLOEXEC) = 15
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
```

#### `/system/bin/cat`

```shell
~ $ strace -f prlimit --verbose -n30 /system/bin/cat x x x x x 2>&1 | grep open | grep -E '/lib(64
)/' | grep -v ENOENT | sort | uniq | wc  -l
20

~ $ strace -f prlimit --verbose -n20: /system/bin/cat x x x x x 2>&1 | grep open | grep -E '/lib(6
4)/' | grep -v ENOENT
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libcrypto.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libz.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/liblog.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libprocessgroup.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libselinux.so", O_RDONLY|O_CLOEXEC) = 7
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 8
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 9
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 10
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 11
openat(AT_FDCWD, "/system/lib64/libbase.so", O_RDONLY|O_CLOEXEC) = 12
openat(AT_FDCWD, "/system/lib64/libcgrouprc.so", O_RDONLY|O_CLOEXEC) = 13
openat(AT_FDCWD, "/system/lib64/libpcre2.so", O_RDONLY|O_CLOEXEC) = 14
openat(AT_FDCWD, "/system/lib64/libpackagelistparser.so", O_RDONLY|O_CLOEXEC) = 15
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
~ $ echo $?
0

~ $ strace -f prlimit --verbose -n15: /system/bin/cat x x x x x 2>&1 | grep open | grep -E '/lib(6
4)/' | grep -v ENOENT
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libcrypto.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libz.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/liblog.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libprocessgroup.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libselinux.so", O_RDONLY|O_CLOEXEC) = 7
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 8
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 9
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 10
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 11
openat(AT_FDCWD, "/system/lib64/libbase.so", O_RDONLY|O_CLOEXEC) = 12
openat(AT_FDCWD, "/system/lib64/libcgrouprc.so", O_RDONLY|O_CLOEXEC) = 13
openat(AT_FDCWD, "/system/lib64/libpcre2.so", O_RDONLY|O_CLOEXEC) = 14
openat(AT_FDCWD, "/system/lib64/libpackagelistparser.so", O_RDONLY|O_CLOEXEC) = -1 EMFILE (Too man
y open files)
openat(AT_FDCWD, "/system_ext/lib64/libpackagelistparser.so", O_RDONLY|O_CLOEXEC) = -1 EMFILE (Too
 many open files)
openat(AT_FDCWD, "/product/lib64/libpackagelistparser.so", O_RDONLY|O_CLOEXEC) = -1 EMFILE (Too ma
ny open files)

~ $ strace -f prlimit --verbose -n16: /system/bin/cat x x x x x 2>&1 | grep open | grep -E '/lib(6
4)/' | grep -v ENOENT
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libcrypto.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libz.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/liblog.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libprocessgroup.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libselinux.so", O_RDONLY|O_CLOEXEC) = 7
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 8
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 9
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 10
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 11
openat(AT_FDCWD, "/system/lib64/libbase.so", O_RDONLY|O_CLOEXEC) = 12
openat(AT_FDCWD, "/system/lib64/libcgrouprc.so", O_RDONLY|O_CLOEXEC) = 13
openat(AT_FDCWD, "/system/lib64/libpcre2.so", O_RDONLY|O_CLOEXEC) = 14
openat(AT_FDCWD, "/system/lib64/libpackagelistparser.so", O_RDONLY|O_CLOEXEC) = 15
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
~ $ echo $?                                                                                       
0
```


#### `$TERMUX__PREFIX/bin/cat`

```shell
~ $ strace -f prlimit --verbose -n30 cat x x x x x 2>&1 | grep open | grep -E '/lib(64
)/' | grep -v ENOENT | sort | uniq | wc  -l
12

~ $ strace -f prlimit --verbose -n20: cat x x x x x 2>&1 | grep open | grep -E '/lib(64)/' | grep 
-v ENOENT
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 8
openat(AT_FDCWD, "/system/lib64/liblog.so", O_RDONLY|O_CLOEXEC) = 10
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 11
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 12
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 13
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
~ $ echo $?                                                                                       
0

~ $ strace -f prlimit --verbose -n13: cat x x x x x 2>&1 | grep open | grep -E '/lib(64)/' | grep 
-v ENOENT
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 8
openat(AT_FDCWD, "/system/lib64/liblog.so", O_RDONLY|O_CLOEXEC) = 10
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 11
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 12
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = -1 EMFILE (Too many open files)
openat(AT_FDCWD, "/system_ext/lib64/libm.so", O_RDONLY|O_CLOEXEC) = -1 EMFILE (Too many open files
)
openat(AT_FDCWD, "/product/lib64/libm.so", O_RDONLY|O_CLOEXEC) = -1 EMFILE (Too many open files)

~ $ strace -f prlimit --verbose -n14: cat x x x x x 2>&1 | grep open | grep -E '/lib(64)/' | grep 
-v ENOENT
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 8
openat(AT_FDCWD, "/system/lib64/liblog.so", O_RDONLY|O_CLOEXEC) = 10
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 11
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 12
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 13
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3
~ $ echo $?                                                                                       
0
```

#### Extra

```shell
~ $ echo $LD_PRELOAD                                                                              
/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so



~ $ TERMUX_EXEC__LOG_LEVEL=4 prlimit --verbose -n3: cat x x x x x
30231 E termux  : TERMUX_EXEC__VERSION: 'libtermux-exec-direct-ld-preload version=1:2.2.0 org=term
ux project=termux-exec-package'
30231 E termux.exec: <----- execve() intercepted ----->
30231 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/prlimit'
30231 E termux.exec:    argv[0] = 'prlimit'
30231 E termux.exec:    argv[1] = '--verbose'
30231 E termux.exec:    argv[2] = '-n3:'
30231 E termux.exec:    argv[3] = 'cat'
30231 E termux.exec:    argv[4] = 'x'
30231 E termux.exec:    argv[5] = 'x'
30231 E termux.exec:    argv[6] = 'x'
30231 E termux.exec:    argv[7] = 'x'
30231 E termux.exec:    argv[8] = 'x'
30231 E termux.exec: Intercepting execve
30231 E termux.exec: read_file_header: '1'
30231 E termux.ld-preload: system_linker_exec_mode: '1'
30231 E termux.ld-preload: android_build_version_sdk: '30'
30231 E termux.ld-preload: se_process_context_from_file: 'u:r:untrusted_app_27:s0:c212,c256,c512,c
768'
30231 E termux.ld-preload: app_data_file_exec_exempted: '1'
30231 E termux.ld-preload: system_linker_exec_enabled: '0'
30231 E termux.exec: unset_ld_vars_from_env: '0'
30231 E termux.exec: modify_env: '0'
30231 E termux.exec: modify_args: '0'
30231 E termux.exec: Calling syscall execve
30231 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/prlimit'
30231 E termux.exec:    argv[0] = 'prlimit'
30231 E termux.exec:    argv[1] = '--verbose'
30231 E termux.exec:    argv[2] = '-n3:'
30231 E termux.exec:    argv[3] = 'cat'
30231 E termux.exec:    argv[4] = 'x'
30231 E termux.exec:    argv[5] = 'x'
30231 E termux.exec:    argv[6] = 'x'
30231 E termux.exec:    argv[7] = 'x'
30231 E termux.exec:    argv[8] = 'x'
New NOFILE limit for pid 30231: <3:32768>
30231 E termux  : TERMUX_EXEC__VERSION: 'libtermux-exec-direct-ld-preload version=1:2.2.0 org=term
ux project=termux-exec-package'
30231 E termux.exec: <----- execvp() intercepted ----->
30231 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/cat'
30231 E termux.exec:    argv[0] = 'cat'
30231 E termux.exec:    argv[1] = 'x'
30231 E termux.exec:    argv[2] = 'x'
30231 E termux.exec:    argv[3] = 'x'
30231 E termux.exec:    argv[4] = 'x'
30231 E termux.exec:    argv[5] = 'x'
30231 E termux.exec: Intercepting execve
30231 E termux.exec: read_file_header: '1'
30231 E termux.exec: Failed to open executable path '/data/data/com.termux/files/usr/bin/cat' for 
file header: Too many open files
30231 E termux.exec: <----- execve() failed ----->
prlimit: failed to execute cat: Too many open files
prlimit: write error: Too many open files



~ $ TERMUX_EXEC__LOG_LEVEL=4 prlimit --verbose -n13: cat x x x x x
30236 E termux  : TERMUX_EXEC__VERSION: 'libtermux-exec-direct-ld-preload version=1:2.2.0 org=term
ux project=termux-exec-package'
30236 E termux.exec: <----- execve() intercepted ----->
30236 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/prlimit'
30236 E termux.exec:    argv[0] = 'prlimit'
30236 E termux.exec:    argv[1] = '--verbose'
30236 E termux.exec:    argv[2] = '-n13:'
30236 E termux.exec:    argv[3] = 'cat'
30236 E termux.exec:    argv[4] = 'x'
30236 E termux.exec:    argv[5] = 'x'
30236 E termux.exec:    argv[6] = 'x'
30236 E termux.exec:    argv[7] = 'x'
30236 E termux.exec:    argv[8] = 'x'
30236 E termux.exec: Intercepting execve
30236 E termux.exec: read_file_header: '1'
30236 E termux.ld-preload: system_linker_exec_mode: '1'
30236 E termux.ld-preload: android_build_version_sdk: '30'
30236 E termux.ld-preload: se_process_context_from_file: 'u:r:untrusted_app_27:s0:c212,c256,c512,c
768'
30236 E termux.ld-preload: app_data_file_exec_exempted: '1'
30236 E termux.ld-preload: system_linker_exec_enabled: '0'
30236 E termux.exec: unset_ld_vars_from_env: '0'
30236 E termux.exec: modify_env: '0'
30236 E termux.exec: modify_args: '0'
30236 E termux.exec: Calling syscall execve
30236 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/prlimit'
30236 E termux.exec:    argv[0] = 'prlimit'
30236 E termux.exec:    argv[1] = '--verbose'
30236 E termux.exec:    argv[2] = '-n13:'
30236 E termux.exec:    argv[3] = 'cat'
30236 E termux.exec:    argv[4] = 'x'
30236 E termux.exec:    argv[5] = 'x'
30236 E termux.exec:    argv[6] = 'x'
30236 E termux.exec:    argv[7] = 'x'
30236 E termux.exec:    argv[8] = 'x'
New NOFILE limit for pid 30236: <13:32768>
30236 E termux  : TERMUX_EXEC__VERSION: 'libtermux-exec-direct-ld-preload version=1:2.2.0 org=term
ux project=termux-exec-package'
30236 E termux.exec: <----- execvp() intercepted ----->
30236 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/cat'
30236 E termux.exec:    argv[0] = 'cat'
30236 E termux.exec:    argv[1] = 'x'
30236 E termux.exec:    argv[2] = 'x'
30236 E termux.exec:    argv[3] = 'x'
30236 E termux.exec:    argv[4] = 'x'
30236 E termux.exec:    argv[5] = 'x'
30236 E termux.exec: Intercepting execve
30236 E termux.exec: read_file_header: '1'
30236 E termux.ld-preload: system_linker_exec_mode: '1'
30236 E termux.ld-preload: android_build_version_sdk: '30'
30236 E termux.ld-preload: se_process_context_from_file: 'u:r:untrusted_app_27:s0:c212,c256,c512,c
768'
30236 E termux.ld-preload: app_data_file_exec_exempted: '1'
30236 E termux.ld-preload: system_linker_exec_enabled: '0'
30236 E termux.exec: unset_ld_vars_from_env: '0'
30236 E termux.exec: modify_env: '0'
30236 E termux.exec: modify_args: '0'
30236 E termux.exec: Calling syscall execve
30236 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/cat'
30236 E termux.exec:    argv[0] = 'cat'
30236 E termux.exec:    argv[1] = 'x'
30236 E termux.exec:    argv[2] = 'x'
30236 E termux.exec:    argv[3] = 'x'
30236 E termux.exec:    argv[4] = 'x'
30236 E termux.exec:    argv[5] = 'x'
CANNOT LINK EXECUTABLE "cat": library "libm.so" not found: needed by /system/lib64/liblog.so in na
mespace (default)



~ $ TERMUX_EXEC__LOG_LEVEL=4 prlimit --verbose -n14: cat x x x x x
30222 E termux  : TERMUX_EXEC__VERSION: 'libtermux-exec-direct-ld-preload version=1:2.2.0 org=term
ux project=termux-exec-package'
30222 E termux.exec: <----- execve() intercepted ----->
30222 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/prlimit'
30222 E termux.exec:    argv[0] = 'prlimit'
30222 E termux.exec:    argv[1] = '--verbose'
30222 E termux.exec:    argv[2] = '-n14:'
30222 E termux.exec:    argv[3] = 'cat'
30222 E termux.exec:    argv[4] = 'x'
30222 E termux.exec:    argv[5] = 'x'
30222 E termux.exec:    argv[6] = 'x'
30222 E termux.exec:    argv[7] = 'x'
30222 E termux.exec:    argv[8] = 'x'
30222 E termux.exec: Intercepting execve
30222 E termux.exec: read_file_header: '1'
30222 E termux.ld-preload: system_linker_exec_mode: '1'
30222 E termux.ld-preload: android_build_version_sdk: '30'
30222 E termux.ld-preload: se_process_context_from_file: 'u:r:untrusted_app_27:s0:c212,c256,c512,c
768'
30222 E termux.ld-preload: app_data_file_exec_exempted: '1'
30222 E termux.ld-preload: system_linker_exec_enabled: '0'
30222 E termux.exec: unset_ld_vars_from_env: '0'
30222 E termux.exec: modify_env: '0'
30222 E termux.exec: modify_args: '0'
30222 E termux.exec: Calling syscall execve
30222 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/prlimit'
30222 E termux.exec:    argv[0] = 'prlimit'
30222 E termux.exec:    argv[1] = '--verbose'
30222 E termux.exec:    argv[2] = '-n14:'
30222 E termux.exec:    argv[3] = 'cat'
30222 E termux.exec:    argv[4] = 'x'
30222 E termux.exec:    argv[5] = 'x'
30222 E termux.exec:    argv[6] = 'x'
30222 E termux.exec:    argv[7] = 'x'
30222 E termux.exec:    argv[8] = 'x'
New NOFILE limit for pid 30222: <14:32768>
30222 E termux  : TERMUX_EXEC__VERSION: 'libtermux-exec-direct-ld-preload version=1:2.2.0 org=term
ux project=termux-exec-package'
30222 E termux.exec: <----- execvp() intercepted ----->
30222 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/cat'
30222 E termux.exec:    argv[0] = 'cat'
30222 E termux.exec:    argv[1] = 'x'
30222 E termux.exec:    argv[2] = 'x'
30222 E termux.exec:    argv[3] = 'x'
30222 E termux.exec:    argv[4] = 'x'
30222 E termux.exec:    argv[5] = 'x'
30222 E termux.exec: Intercepting execve
30222 E termux.exec: read_file_header: '1'
30222 E termux.ld-preload: system_linker_exec_mode: '1'
30222 E termux.ld-preload: android_build_version_sdk: '30'
30222 E termux.ld-preload: se_process_context_from_file: 'u:r:untrusted_app_27:s0:c212,c256,c512,c
768'
30222 E termux.ld-preload: app_data_file_exec_exempted: '1'
30222 E termux.ld-preload: system_linker_exec_enabled: '0'
30222 E termux.exec: unset_ld_vars_from_env: '0'
30222 E termux.exec: modify_env: '0'
30222 E termux.exec: modify_args: '0'
30222 E termux.exec: Calling syscall execve
30222 E termux.exec: executable = '/data/data/com.termux/files/usr/bin/cat'
30222 E termux.exec:    argv[0] = 'cat'
30222 E termux.exec:    argv[1] = 'x'
30222 E termux.exec:    argv[2] = 'x'
30222 E termux.exec:    argv[3] = 'x'
30222 E termux.exec:    argv[4] = 'x'
30222 E termux.exec:    argv[5] = 'x'
~ $ echo $?
0

~ $ prlimit --verbose -n14: cat x x x x x                                                         
New NOFILE limit for pid 30141: <14:32768>
~ $ echo $?
0



~ $ prlimit --verbose -n13: cat x x x x x
New NOFILE limit for pid 30933: <13:32768>
CANNOT LINK EXECUTABLE "cat": library "libm.so" not found: needed by /system/lib64/liblog.so in na
mespace (default)



~ $ dpkg -i /sdcard/termux-exec1.deb
(Reading database ... 61123 files and directories currently installed.)
Preparing to unpack /sdcard/termux-exec1.deb ...
Unpacking termux-exec (1:1.0-1) over (1:1.0-1) ...
Setting up termux-exec (1:1.0-1) ...

# Restart shell

~ $ prlimit --verbose -n13: cat x x x x x
New NOFILE limit for pid 31331: <13:32768>
CANNOT LINK EXECUTABLE "cat": library "libm.so" not found: needed by /system/lib64/liblog.so in namespace (default)

~ $ prlimit --verbose -n14: cat x x x x x
New NOFILE limit for pid 31335: <14:32768>
```

**Comment by agnostic-apollo** [comment]
There is a typo in the regex, missed a `?`, it should be `grep -E '/lib(64)?/'` to list termux libraries, but hopefully you get the idea.

To dynamically find the limit required, including the libraries opened, you can do something like following, where `+ 1` is for the fd required to open one `x` file at a time with `cat`.

```shell
 $ strace -f cat --help 2>&1 | grep open | grep -E '/lib(64)?/' | grep -v ENOENT
openat(AT_FDCWD, "/vendor/lib64/egl", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/vendor/lib64/hw", O_RDONLY|O_CLOEXEC|O_PATH) = 3
openat(AT_FDCWD, "/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/data/data/com.termux/files/usr/lib/libandroid-support.so", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/data/data/com.termux/files/usr/lib/libandroid-selinux.so", O_RDONLY|O_CLOEXEC) = 5
openat(AT_FDCWD, "/data/data/com.termux/files/usr/lib/libgmp.so", O_RDONLY|O_CLOEXEC) = 6
openat(AT_FDCWD, "/data/data/com.termux/files/usr/lib/libiconv.so", O_RDONLY|O_CLOEXEC) = 7
openat(AT_FDCWD, "/system/lib64/libc.so", O_RDONLY|O_CLOEXEC) = 8
openat(AT_FDCWD, "/data/data/com.termux/files/usr/lib/libpcre2-8.so", O_RDONLY|O_CLOEXEC) = 9
openat(AT_FDCWD, "/system/lib64/liblog.so", O_RDONLY|O_CLOEXEC) = 10
openat(AT_FDCWD, "/system/lib64/libdl.so", O_RDONLY|O_CLOEXEC) = 11
openat(AT_FDCWD, "/system/lib64/libc++.so", O_RDONLY|O_CLOEXEC) = 12
openat(AT_FDCWD, "/system/lib64/libm.so", O_RDONLY|O_CLOEXEC) = 13
openat(AT_FDCWD, "/system/lib64/libnetd_client.so", O_RDONLY|O_CLOEXEC) = 3

limit="$(strace -f cat --help 2>&1 | grep open | grep -E '/lib(64)?/' | grep -v ENOENT | sed -E 's/^.* = ([0-9]+)$/\1/g' | sort -n | tail -n 1)"
$ echo "$limit"
13

$ prlimit --verbose -n$((limit + 1)): cat x x x x x
New NOFILE limit for pid 28398: <14:32768>

$ prlimit --verbose -n$((limit)): cat x x x x x
New NOFILE limit for pid 28406: <13:32768>
CANNOT LINK EXECUTABLE "cat": library "libm.so" not found: needed by /system/lib64/liblog.so in namespace (default)
```

**Comment by drinkcat** [comment]
Oh, this is really interesting, thanks for running experiments!

For background, we're running a Rust executable, so the number of dynamic libraries should be fairly small (but still quite a bit larger than what is required on Linux).

First thing that springs to mind, the ELF interpreter on Linux is closing fds much more aggressively after loading the libraries, so the number of open fds stays really really low and is much less likely to hit `prlimit`:
```
strace /bin/rsync 2>&1 | grep openat # I use rsync as that has a good number of required libraries
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libacl.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libpopt.so.0", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/liblz4.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libzstd.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libxxhash.so.0", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libcrypto.so.3", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/ssl/openssl.cnf", O_RDONLY) = 3
```
That's, of course, out of termux control.

What I wonder though... How many other libraries does your preloaded library actually need? (that is what does `ldd $LD_PRELOAD` say, vs what is needed for both versions of `cat`) I wonder if that's causing the number of loaded libraries to increase (so the number of opened fd due to Android's interpreter behaviour).

**Comment by agnostic-apollo** [comment]
Yeah, we can't do anything for the libraries loaded, you will have to modify the tests.

`libtermux-exec*.so` doesn't really depend on any extra libraries. It's the `cat` that do. For `cat` provided by Termux, it would depend on libraries linked during compilation via package dependencies at https://github.com/termux/termux-packages/blob/d34bc59e2b9b16bbad5bfc6c58d3e73fd67b2b2f/packages/coreutils/build.sh#L9 recursively.

```shell
~ $ ldd $LD_PRELOAD
        libc.so => /system/lib64/libc.so
        ld-android.so => /system/lib64/ld-android.so
        libdl.so => /system/lib64/libdl.so
~ $ ldd $PREFIX/bin/cat
        libandroid-support.so => /data/data/com.termux/files/usr/lib/libandroid-support.so
        libandroid-selinux.so => /data/data/com.termux/files/usr/lib/libandroid-selinux.so
        libgmp.so => /data/data/com.termux/files/usr/lib/libgmp.so
        libiconv.so => /data/data/com.termux/files/usr/lib/libiconv.so
        libc.so => /system/lib64/libc.so
        ld-android.so => /system/lib64/ld-android.so
        libdl.so => /system/lib64/libdl.so
        libpcre2-8.so => /data/data/com.termux/files/usr/lib/libpcre2-8.so
        liblog.so => /system/lib64/liblog.so
        libc++.so => /system/lib64/libc++.so
        libm.so => /system/lib64/libm.so
~ $ ldd /system/bin/cat
        libcrypto.so => /system/lib64/libcrypto.so
        libz.so => /system/lib64/libz.so
        liblog.so => /system/lib64/liblog.so
        libprocessgroup.so => /system/lib64/libprocessgroup.so
        libselinux.so => /system/lib64/libselinux.so
        libc.so => /system/lib64/libc.so
        libm.so => /system/lib64/libm.so
        libdl.so => /system/lib64/libdl.so
        ld-android.so => /system/lib64/ld-android.so
        libc++.so => /system/lib64/libc++.so
        libbase.so => /system/lib64/libbase.so
        libcgrouprc.so => /system/lib64/libcgrouprc.so
        libpcre2.so => /system/lib64/libpcre2.so
        libpackagelistparser.so => /system/lib64/libpackagelistparser.so
```

**Comment by drinkcat** [comment]
Thanks a lot for your help, I really appreciate how deep you dug into this, even as it's becoming very clear that it's not a termux issue.

It's still not clear to me why this issue suddenly appeared, but I think I have enough ideas about how I can modify the tests now, and keep at least some amount of coverage.

**Comment by agnostic-apollo** [comment]
You are welcome. Goodluck.
